CREATE TABLE BPI (
 ID VARCHAR(36) PRIMARY KEY,
 NAME VARCHAR(15) DEFAULT NULL,
 CODE VARCHAR(3) DEFAULT NULL,
 SYMBOL VARCHAR(20) DEFAULT NULL,
 RATE VARCHAR(20) DEFAULT NULL,
 DESCRIPTION VARCHAR(30) DEFAULT NULL,
 RATE_FLOAT FLOAT(10) DEFAULT 0.0
);

CREATE TABLE TEST_TIME (
 ID VARCHAR(36) PRIMARY KEY,
 UPDATED DATE DEFAULT NULL,
 UPDATED_ISO DATE DEFAULT NULL,
 UPDATE_DUK DATE DEFAULT NULL
);

CREATE TABLE CURRENCY (
 ID VARCHAR(36) PRIMARY KEY,
 NAME VARCHAR(15) DEFAULT NULL,
 CODE VARCHAR(3) DEFAULT NULL,
 RATE VARCHAR(20) DEFAULT NULL,
);